pipeline{
    agent any
    stages{
        stage("Build Frontend"){
            steps{
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/gonzaloArevalo/Lab1_tingeso']])
                dir("Prestamo_frontend"){
                    sh "npm install"
                    sh "npm run build"
                }
            }
        }
        stage("Build and Push Docker Image"){
            steps{
                dir("Prestamo_frontend"){
                    script{
                         withDockerRegistry(credentialsId: 'docker-credentials'){
                            sh "docker build -t 746778/prestamo-frontend:latest ."
                            sh "docker push 746778/prestamo-frontend:latest"
                        }
                    }                    
                }
            }
        }
    }
}